### ISSUE TITLE
Unneeded dependencies

### ISSUE THREAD

**Issue by maelle** [ropensci-org/rodev#38]
You could store many unneeded Suggests without R CMD Check giving any warning.

```r
desc_deps <- attachment::att_from_description()
scripts_deps <- attachment::att_from_rscripts(".")
namespace_deps <- attachment::att_from_namespace()
vignette_deps <- attachment::att_from_rmds()
desc_deps[!desc_deps %in% c(scripts_deps, namespace_deps, vignette_deps)]
```

**Comment by maelle** [comment]
there are limits to the above. run it on pak.

**Comment by maelle** [comment]
@mpadge is this something checked by pkgcheck?

**Comment by mpadge** [comment]
Not directly, but since `pkgcheck` runs `rcmdcheck`, these checks are picked up there. It could be a good one to integrate into a direct check, but we will also need to be careful with that, because it could be a proverbial can o'worms. Maybe best to have an initial policy that any checks that are covered elsewhere, no matter how indirectly, ought not be integrated into `pkgcheck` until ... some arbitrary later time when we have a bit more insight. Happy to hear any opinions to the contrary, but those would be my initial thoughts.

**Comment by maelle** [comment]
Thank you! But R CMD check doesn't check the use of Suggests packages?
